/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views.formScreen;

import java.awt.Cursor;

/**
 *
 * @author adimael
 */
public class CadastroUserDialog extends javax.swing.JDialog {

    /**
     * Creates new form CadastroUserDialog
     */
    public CadastroUserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        btnCadastrar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnCancelar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        placeHolderUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        placeHolderPassword = new javax.swing.JLabel();
        placeHolderUsername = new javax.swing.JLabel();
        placeHolderPassword1 = new javax.swing.JLabel();
        placeHolderPassword2 = new javax.swing.JLabel();
        jUsernameField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jNivelAcesso = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();

        placeHolderUser.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        placeHolderUser.setForeground(new java.awt.Color(153, 153, 153));
        placeHolderUser.setText("Digite seu nome de usuário....");
        placeHolderUser.setEnabled(false);
        placeHolderUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placeHolderUserKeyTyped(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1700, 810));
        setPreferredSize(new java.awt.Dimension(1700, 810));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("*");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 20, -1));

        jLabel7.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("*");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 20, -1));

        placeHolderPassword.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        placeHolderPassword.setForeground(new java.awt.Color(153, 153, 153));
        placeHolderPassword.setText("Digite o nome da pessoa....");
        placeHolderPassword.setEnabled(false);
        placeHolderPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placeHolderPasswordKeyTyped(evt);
            }
        });
        jPanel2.add(placeHolderPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 480, 60));

        placeHolderUsername.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        placeHolderUsername.setForeground(new java.awt.Color(153, 153, 153));
        placeHolderUsername.setText("Username... Ex: fulano.silva");
        placeHolderUsername.setEnabled(false);
        placeHolderUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placeHolderUsernameKeyTyped(evt);
            }
        });
        jPanel2.add(placeHolderUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 510, 60));

        placeHolderPassword1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        placeHolderPassword1.setForeground(new java.awt.Color(153, 153, 153));
        placeHolderPassword1.setText("Confirmar senha....");
        placeHolderPassword1.setEnabled(false);
        placeHolderPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placeHolderPassword1KeyTyped(evt);
            }
        });
        jPanel2.add(placeHolderPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 480, 60));

        placeHolderPassword2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        placeHolderPassword2.setForeground(new java.awt.Color(153, 153, 153));
        placeHolderPassword2.setText("Senha....");
        placeHolderPassword2.setEnabled(false);
        placeHolderPassword2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placeHolderPassword2KeyTyped(evt);
            }
        });
        jPanel2.add(placeHolderPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 480, 60));

        jUsernameField.setBackground(new java.awt.Color(204, 255, 204));
        jUsernameField.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jUsernameField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jUsernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jUsernameFieldKeyReleased(evt);
            }
        });
        jPanel2.add(jUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 520, 60));

        jLabel8.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("*");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 130, 20, -1));

        jLabel3.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Dados de Acesso");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Senha");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        jLabel20.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Confirmar senha");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(204, 255, 204));
        jPasswordField1.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 520, 60));

        jPasswordField.setBackground(new java.awt.Color(204, 255, 204));
        jPasswordField.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jPasswordField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordFieldKeyReleased(evt);
            }
        });
        jPanel2.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 520, 60));

        jLabel21.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Nome da pessoa");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, -1, -1));

        jPasswordField2.setBackground(new java.awt.Color(204, 255, 204));
        jPasswordField2.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jPasswordField2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
        });
        jPanel2.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 520, 60));

        jLabel22.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Username");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("*");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 20, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1712, -1));

        jLabel2.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 410, 20, -1));

        jLabel4.setFont(new java.awt.Font("Inter", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Cadastrar novo usuário");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Obs: Todos os campos obrigatórios possuem o símbolo '*'. Por favor preencher corretamente.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 830, -1));

        btnCadastrar.setBackground(new java.awt.Color(204, 255, 204));
        btnCadastrar.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnCadastrar.setMaximumSize(new java.awt.Dimension(1290, 760));
        btnCadastrar.setMinimumSize(new java.awt.Dimension(1290, 760));
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 470, 170, 60));

        btnCancelar.setBackground(new java.awt.Color(255, 153, 153));
        btnCancelar.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 51, 51));
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 470, 190, 60));

        jNivelAcesso.setBackground(new java.awt.Color(204, 255, 204));
        jNivelAcesso.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jNivelAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o nível de acesso...", "Administrador", "Usuário comum" }));
        jPanel1.add(jNivelAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 430, 40));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setToolTipText("");
        jScrollPane1.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 520, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void placeHolderUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeHolderUserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_placeHolderUserKeyTyped

    private void placeHolderPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeHolderPasswordKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_placeHolderPasswordKeyTyped

    private void placeHolderUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeHolderUsernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_placeHolderUsernameKeyTyped

    private void jUsernameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameFieldKeyReleased
        // TODO add your handling code here:
        if(jUsernameField.getText().isEmpty()) {
            placeHolderUsername.setVisible(true);
            placeHolderUsername.setEnabled(false);
        } else {
            placeHolderUsername.setVisible(false);
            placeHolderUsername.setEnabled(false);
        }
    }//GEN-LAST:event_jUsernameFieldKeyReleased

    private void jPasswordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldKeyReleased
        // TODO add your handling code here:
        if (new String(jPasswordField.getPassword()).isEmpty()) {
            placeHolderPassword.setVisible(true);
            placeHolderPassword.setEnabled(false);
        } else {
            placeHolderPassword.setVisible(false);
            placeHolderPassword.setEnabled(false);
        }
    }//GEN-LAST:event_jPasswordFieldKeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void placeHolderPassword1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeHolderPassword1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_placeHolderPassword1KeyTyped

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void placeHolderPassword2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeHolderPassword2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_placeHolderPassword2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUserDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroUserDialog dialog = new CadastroUserDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jNivelAcesso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jUsernameField;
    private javax.swing.JLabel placeHolderPassword;
    private javax.swing.JLabel placeHolderPassword1;
    private javax.swing.JLabel placeHolderPassword2;
    private javax.swing.JLabel placeHolderUser;
    private javax.swing.JLabel placeHolderUsername;
    // End of variables declaration//GEN-END:variables
}
