/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import views.formScreen.VisualizarHistoricoDialog;
import views.formScreen.CadastroUserDialog;
import java.awt.Color;
import java.awt.Cursor;
import java.net.URL;
import javax.swing.ImageIcon;
import views.formScreen.CadastroPessoaDialog;
import views.formScreen.CadastroSalaDialog;
import views.formScreen.VisualizarSalasDialog;
import views.formScreen.VisualizarUserDialog;

/**
 *
 * @author adimael
 */
public class DashboardScreen extends javax.swing.JFrame {

    /**
     * Creates new form DashboardScreen
     */
    public DashboardScreen() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        URL txtDashboardIcon = getClass().getResource("/icons/data-analysis32.png");
        btnDashboard.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        if (txtDashboardIcon != null) {
            txtDashboard.setIcon(new ImageIcon(txtDashboardIcon));
        } else {
            System.out.println("icone do btnDashboard não foi encontrado!");
        }
        
        //Icon Menu usuários
        URL txtUsuariosIcon = getClass().getResource("/icons/team.png");
        URL txtSeta1Icon = getClass().getResource("/icons/left-arrow.png");
        URL txtAddUserIcon = getClass().getResource("/icons/sign-up (1).png");
        URL txtVisualizarUsersIcon = getClass().getResource("/icons/log.png");
        btnMenuUsuario.setCursor(new Cursor(Cursor.HAND_CURSOR));
        itemAddUser.setCursor(new Cursor(Cursor.HAND_CURSOR));
        itemHistoricoUsers.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        if (txtUsuariosIcon != null && txtSeta1Icon != null && txtAddUserIcon != null && txtVisualizarUsersIcon != null) {
            txtUsuarios.setIcon(new ImageIcon(txtUsuariosIcon));
            iconSeta1.setIcon(new ImageIcon(txtSeta1Icon));
            txtAddUser.setIcon(new ImageIcon(txtAddUserIcon));
            txtHistoricoUsers.setIcon(new ImageIcon(txtVisualizarUsersIcon));
        } else {
            System.out.println("Icone Menu Usuários não foi encontrado!");
        }
        
        
        
        //Icon Menu Gerenciamento de Salas
        URL txtGenSalasIcon = getClass().getResource("/icons/door.png");
        URL iconSeta2Icon = getClass().getResource("/icons/left-arrow.png");
        URL txtAddSalaIcon = getClass().getResource("/icons/door (1).png");
        URL txtVisualizarSalaIcon = getClass().getResource("/icons/man (1).png");
        URL txtHistoricoChavesIcon = getClass().getResource("/icons/hold_2921771.png");
        btnMenuGenSalas.setCursor(new Cursor(Cursor.HAND_CURSOR));
        itemAddSala.setCursor(new Cursor(Cursor.HAND_CURSOR));
        itemVisualizarSalas.setCursor(new Cursor(Cursor.HAND_CURSOR));
        itemHistoricoChaves.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        if (txtGenSalasIcon != null && iconSeta2Icon != null && txtAddSalaIcon != null && txtVisualizarSalaIcon != null && txtHistoricoChavesIcon != null) {
            txtGenSalas.setIcon(new ImageIcon(txtGenSalasIcon));
            iconSeta2.setIcon(new ImageIcon(iconSeta2Icon));
            txtAddSala.setIcon(new ImageIcon(txtAddSalaIcon));
            txtVisualizarSala.setIcon(new ImageIcon(txtVisualizarSalaIcon));
            txtHistoricoChaves.setIcon(new ImageIcon(txtHistoricoChavesIcon));
        } else {
            System.out.println("Icone Menu Gerenciamento de chaves não foi encontrado!");
        }
        
        //Icon Menu do Perfil do Usuário
        URL txtNomeUserIcon = getClass().getResource("/icons/man_4140037.png");
        URL txtSeta3Icon = getClass().getResource("/icons/left-arrow.png");
        URL txtPerfilIcon = getClass().getResource("/icons/user32.png");
        URL txtConfiguraçõesIcon = getClass().getResource("/icons/settings.png");
        URL txtSuporteIcon = getClass().getResource("/icons/request (1).png");
        URL txtSairIcon = getClass().getResource("/icons/check-out (1).png");
        btnMenuUser.setCursor(new Cursor(Cursor.HAND_CURSOR));
        itemSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        if (txtNomeUserIcon != null && txtSeta3Icon != null && txtPerfilIcon != null && txtConfiguraçõesIcon != null && txtSuporteIcon != null && txtSairIcon != null) {
            txtNomeUser.setIcon(new ImageIcon(txtNomeUserIcon));
            txtSeta3.setIcon(new ImageIcon(txtSeta3Icon));
            txtSair.setIcon(new ImageIcon(txtSairIcon));
        } else {
            System.out.println("Icone Menu do usuário não foi encontrado!");
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JPanel();
        txtDashboard = new javax.swing.JLabel();
        btnMenuUsuario = new javax.swing.JPanel();
        txtUsuarios = new javax.swing.JLabel();
        iconSeta1 = new javax.swing.JLabel();
        btnMenuGenSalas = new javax.swing.JPanel();
        txtGenSalas = new javax.swing.JLabel();
        iconSeta2 = new javax.swing.JLabel();
        btnMenuUser = new javax.swing.JPanel();
        txtNomeUser = new javax.swing.JLabel();
        txtSeta3 = new javax.swing.JLabel();
        jmenu = new javax.swing.JPanel();
        itemAddUser = new javax.swing.JPanel();
        txtAddUser = new javax.swing.JLabel();
        itemHistoricoUsers = new javax.swing.JPanel();
        txtHistoricoUsers = new javax.swing.JLabel();
        itemAddPessoa = new javax.swing.JPanel();
        txtAddPessoa = new javax.swing.JLabel();
        itemVisualizarUsers1 = new javax.swing.JPanel();
        txtVisualizarUsers1 = new javax.swing.JLabel();
        jmenu1 = new javax.swing.JPanel();
        itemAddSala = new javax.swing.JPanel();
        txtAddSala = new javax.swing.JLabel();
        itemVisualizarSalas = new javax.swing.JPanel();
        txtVisualizarSala = new javax.swing.JLabel();
        itemHistoricoChaves = new javax.swing.JPanel();
        txtHistoricoChaves = new javax.swing.JLabel();
        jmenu2 = new javax.swing.JPanel();
        itemSair = new javax.swing.JPanel();
        txtSair = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        painel1 = new javax.swing.JPanel();
        sala1 = new javax.swing.JButton();
        sala2 = new javax.swing.JButton();
        sala3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        placeHolderNome = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1320, 820));

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
        });

        txtDashboard.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        txtDashboard.setForeground(new java.awt.Color(51, 51, 51));
        txtDashboard.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/data-analysis32.png")); // NOI18N
        txtDashboard.setText("Dashboard");

        javax.swing.GroupLayout btnDashboardLayout = new javax.swing.GroupLayout(btnDashboard);
        btnDashboard.setLayout(btnDashboardLayout);
        btnDashboardLayout.setHorizontalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnDashboardLayout.setVerticalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMenuUsuario.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnMenuUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuUsuarioMouseExited(evt);
            }
        });

        txtUsuarios.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        txtUsuarios.setForeground(new java.awt.Color(51, 51, 51));
        txtUsuarios.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/team.png")); // NOI18N
        txtUsuarios.setText("Usuários");

        iconSeta1.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/left-arrow.png")); // NOI18N

        javax.swing.GroupLayout btnMenuUsuarioLayout = new javax.swing.GroupLayout(btnMenuUsuario);
        btnMenuUsuario.setLayout(btnMenuUsuarioLayout);
        btnMenuUsuarioLayout.setHorizontalGroup(
            btnMenuUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMenuUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconSeta1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        btnMenuUsuarioLayout.setVerticalGroup(
            btnMenuUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenuUsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(btnMenuUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtUsuarios)
                    .addComponent(iconSeta1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMenuGenSalas.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuGenSalas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnMenuGenSalas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuGenSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuGenSalasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuGenSalasMouseExited(evt);
            }
        });

        txtGenSalas.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        txtGenSalas.setForeground(new java.awt.Color(51, 51, 51));
        txtGenSalas.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/door.png")); // NOI18N
        txtGenSalas.setText("Gen. Salas");

        iconSeta2.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/left-arrow.png")); // NOI18N

        javax.swing.GroupLayout btnMenuGenSalasLayout = new javax.swing.GroupLayout(btnMenuGenSalas);
        btnMenuGenSalas.setLayout(btnMenuGenSalasLayout);
        btnMenuGenSalasLayout.setHorizontalGroup(
            btnMenuGenSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnMenuGenSalasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtGenSalas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconSeta2)
                .addGap(10, 10, 10))
        );
        btnMenuGenSalasLayout.setVerticalGroup(
            btnMenuGenSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenuGenSalasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(btnMenuGenSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGenSalas)
                    .addComponent(iconSeta2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnMenuUser.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenuUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuUserMouseExited(evt);
            }
        });

        txtNomeUser.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        txtNomeUser.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/man_4140037.png")); // NOI18N
        txtNomeUser.setText("fulano.silva");

        txtSeta3.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/left-arrow.png")); // NOI18N

        javax.swing.GroupLayout btnMenuUserLayout = new javax.swing.GroupLayout(btnMenuUser);
        btnMenuUser.setLayout(btnMenuUserLayout);
        btnMenuUserLayout.setHorizontalGroup(
            btnMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenuUserLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(txtNomeUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSeta3))
        );
        btnMenuUserLayout.setVerticalGroup(
            btnMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnMenuUserLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(btnMenuUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomeUser)
                    .addComponent(txtSeta3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMenuGenSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMenuUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuGenSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenuUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(198, 198, 198))
        );

        jmenu.setBackground(new java.awt.Color(255, 255, 255));
        jmenu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jmenu.setPreferredSize(new java.awt.Dimension(242, 126));
        jmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmenuMouseExited(evt);
            }
        });

        itemAddUser.setBackground(new java.awt.Color(255, 255, 255));
        itemAddUser.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        itemAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAddUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAddUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemAddUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemAddUserMouseExited(evt);
            }
        });

        txtAddUser.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        txtAddUser.setForeground(new java.awt.Color(51, 51, 51));
        txtAddUser.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/sign-up (1).png")); // NOI18N
        txtAddUser.setText("Add usuário");
        txtAddUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout itemAddUserLayout = new javax.swing.GroupLayout(itemAddUser);
        itemAddUser.setLayout(itemAddUserLayout);
        itemAddUserLayout.setHorizontalGroup(
            itemAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemAddUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAddUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemAddUserLayout.setVerticalGroup(
            itemAddUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemAddUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAddUser)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        itemHistoricoUsers.setBackground(new java.awt.Color(255, 255, 255));
        itemHistoricoUsers.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        itemHistoricoUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemHistoricoUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemHistoricoUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemHistoricoUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemHistoricoUsersMouseExited(evt);
            }
        });

        txtHistoricoUsers.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        txtHistoricoUsers.setForeground(new java.awt.Color(51, 51, 51));
        txtHistoricoUsers.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/log.png")); // NOI18N
        txtHistoricoUsers.setText("Histórico de usuários");
        txtHistoricoUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout itemHistoricoUsersLayout = new javax.swing.GroupLayout(itemHistoricoUsers);
        itemHistoricoUsers.setLayout(itemHistoricoUsersLayout);
        itemHistoricoUsersLayout.setHorizontalGroup(
            itemHistoricoUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemHistoricoUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoricoUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemHistoricoUsersLayout.setVerticalGroup(
            itemHistoricoUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemHistoricoUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoricoUsers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemAddPessoa.setBackground(new java.awt.Color(255, 255, 255));
        itemAddPessoa.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        itemAddPessoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAddPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAddPessoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemAddPessoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemAddPessoaMouseExited(evt);
            }
        });

        txtAddPessoa.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        txtAddPessoa.setForeground(new java.awt.Color(51, 51, 51));
        txtAddPessoa.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/pessoa.png")); // NOI18N
        txtAddPessoa.setText("Cadastrar pessoa");
        txtAddPessoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAddPessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddPessoaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAddPessoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAddPessoaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout itemAddPessoaLayout = new javax.swing.GroupLayout(itemAddPessoa);
        itemAddPessoa.setLayout(itemAddPessoaLayout);
        itemAddPessoaLayout.setHorizontalGroup(
            itemAddPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemAddPessoaLayout.createSequentialGroup()
                .addComponent(txtAddPessoa)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        itemAddPessoaLayout.setVerticalGroup(
            itemAddPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemAddPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAddPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        itemVisualizarUsers1.setBackground(new java.awt.Color(255, 255, 255));
        itemVisualizarUsers1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        itemVisualizarUsers1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVisualizarUsers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemVisualizarUsers1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemVisualizarUsers1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemVisualizarUsers1MouseExited(evt);
            }
        });

        txtVisualizarUsers1.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        txtVisualizarUsers1.setForeground(new java.awt.Color(51, 51, 51));
        txtVisualizarUsers1.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/team32.png")); // NOI18N
        txtVisualizarUsers1.setText("Visualizar usuários");
        txtVisualizarUsers1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtVisualizarUsers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtVisualizarUsers1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtVisualizarUsers1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout itemVisualizarUsers1Layout = new javax.swing.GroupLayout(itemVisualizarUsers1);
        itemVisualizarUsers1.setLayout(itemVisualizarUsers1Layout);
        itemVisualizarUsers1Layout.setHorizontalGroup(
            itemVisualizarUsers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemVisualizarUsers1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVisualizarUsers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemVisualizarUsers1Layout.setVerticalGroup(
            itemVisualizarUsers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemVisualizarUsers1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVisualizarUsers1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jmenuLayout = new javax.swing.GroupLayout(jmenu);
        jmenu.setLayout(jmenuLayout);
        jmenuLayout.setHorizontalGroup(
            jmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(itemVisualizarUsers1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemHistoricoUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemAddUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemAddPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 44, Short.MAX_VALUE))
        );
        jmenuLayout.setVerticalGroup(
            jmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itemAddPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itemVisualizarUsers1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(itemHistoricoUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jmenu1.setBackground(new java.awt.Color(255, 255, 255));
        jmenu1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jmenu1.setPreferredSize(new java.awt.Dimension(242, 126));
        jmenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmenu1MouseExited(evt);
            }
        });

        itemAddSala.setBackground(new java.awt.Color(255, 255, 255));
        itemAddSala.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        itemAddSala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemAddSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAddSalaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemAddSalaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemAddSalaMouseExited(evt);
            }
        });

        txtAddSala.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        txtAddSala.setForeground(new java.awt.Color(51, 51, 51));
        txtAddSala.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/door (1).png")); // NOI18N
        txtAddSala.setText("Add sala");
        txtAddSala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout itemAddSalaLayout = new javax.swing.GroupLayout(itemAddSala);
        itemAddSala.setLayout(itemAddSalaLayout);
        itemAddSalaLayout.setHorizontalGroup(
            itemAddSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemAddSalaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAddSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemAddSalaLayout.setVerticalGroup(
            itemAddSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemAddSalaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAddSala)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        itemVisualizarSalas.setBackground(new java.awt.Color(255, 255, 255));
        itemVisualizarSalas.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        itemVisualizarSalas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemVisualizarSalas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemVisualizarSalasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemVisualizarSalasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemVisualizarSalasMouseExited(evt);
            }
        });

        txtVisualizarSala.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        txtVisualizarSala.setForeground(new java.awt.Color(51, 51, 51));
        txtVisualizarSala.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/man (1).png")); // NOI18N
        txtVisualizarSala.setText("Visualizar salas");
        txtVisualizarSala.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout itemVisualizarSalasLayout = new javax.swing.GroupLayout(itemVisualizarSalas);
        itemVisualizarSalas.setLayout(itemVisualizarSalasLayout);
        itemVisualizarSalasLayout.setHorizontalGroup(
            itemVisualizarSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemVisualizarSalasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVisualizarSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        itemVisualizarSalasLayout.setVerticalGroup(
            itemVisualizarSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemVisualizarSalasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtVisualizarSala)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemHistoricoChaves.setBackground(new java.awt.Color(255, 255, 255));
        itemHistoricoChaves.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        itemHistoricoChaves.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemHistoricoChaves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemHistoricoChavesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemHistoricoChavesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemHistoricoChavesMouseExited(evt);
            }
        });

        txtHistoricoChaves.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        txtHistoricoChaves.setForeground(new java.awt.Color(51, 51, 51));
        txtHistoricoChaves.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/hold_2921771.png")); // NOI18N
        txtHistoricoChaves.setText("Histórico de chaves");
        txtHistoricoChaves.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout itemHistoricoChavesLayout = new javax.swing.GroupLayout(itemHistoricoChaves);
        itemHistoricoChaves.setLayout(itemHistoricoChavesLayout);
        itemHistoricoChavesLayout.setHorizontalGroup(
            itemHistoricoChavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemHistoricoChavesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoricoChaves, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
        );
        itemHistoricoChavesLayout.setVerticalGroup(
            itemHistoricoChavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemHistoricoChavesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtHistoricoChaves)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jmenu1Layout = new javax.swing.GroupLayout(jmenu1);
        jmenu1.setLayout(jmenu1Layout);
        jmenu1Layout.setHorizontalGroup(
            jmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(itemHistoricoChaves, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemVisualizarSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemAddSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 53, Short.MAX_VALUE))
        );
        jmenu1Layout.setVerticalGroup(
            jmenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmenu1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemAddSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itemVisualizarSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itemHistoricoChaves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jmenu2.setBackground(new java.awt.Color(255, 255, 255));
        jmenu2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jmenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jmenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jmenu2MouseExited(evt);
            }
        });

        itemSair.setBackground(new java.awt.Color(255, 255, 255));
        itemSair.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        itemSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemSairMouseExited(evt);
            }
        });

        txtSair.setFont(new java.awt.Font("Inter", 1, 20)); // NOI18N
        txtSair.setForeground(new java.awt.Color(102, 102, 102));
        txtSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSair.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/check-out (1).png")); // NOI18N
        txtSair.setText("Sair");
        txtSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtSair.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout itemSairLayout = new javax.swing.GroupLayout(itemSair);
        itemSair.setLayout(itemSairLayout);
        itemSairLayout.setHorizontalGroup(
            itemSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        itemSairLayout.setVerticalGroup(
            itemSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtSair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jmenu2Layout = new javax.swing.GroupLayout(jmenu2);
        jmenu2.setLayout(jmenu2Layout);
        jmenu2Layout.setHorizontalGroup(
            jmenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmenu2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itemSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jmenu2Layout.setVerticalGroup(
            jmenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmenu2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N

        painel1.setBackground(new java.awt.Color(255, 255, 255));

        sala1.setBackground(new java.awt.Color(102, 255, 102));
        sala1.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        sala1.setForeground(new java.awt.Color(102, 102, 102));
        sala1.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/computer.png")); // NOI18N
        sala1.setText("124 - Laboratório de informática");
        sala1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        sala1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sala2.setBackground(new java.awt.Color(102, 255, 102));
        sala2.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        sala2.setForeground(new java.awt.Color(102, 102, 102));
        sala2.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/biologia.png")); // NOI18N
        sala2.setText("120 - Laboratório de biologia");
        sala2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        sala2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        sala3.setBackground(new java.awt.Color(102, 255, 102));
        sala3.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        sala3.setForeground(new java.awt.Color(102, 102, 102));
        sala3.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/quimica.png")); // NOI18N
        sala3.setText("127 - Laboratório de quimica");
        sala3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        sala3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/icons8-search-32.png")); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        placeHolderNome.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        placeHolderNome.setForeground(new java.awt.Color(153, 153, 153));
        placeHolderNome.setText("Pesquisar....");
        placeHolderNome.setEnabled(false);
        placeHolderNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placeHolderNomeKeyTyped(evt);
            }
        });
        jPanel3.add(placeHolderNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 510, 60));

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.setFont(new java.awt.Font("Inter", 0, 24)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 520, 60));

        javax.swing.GroupLayout painel1Layout = new javax.swing.GroupLayout(painel1);
        painel1.setLayout(painel1Layout);
        painel1Layout.setHorizontalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel1Layout.createSequentialGroup()
                        .addComponent(sala1)
                        .addGap(51, 51, 51)
                        .addComponent(sala2)
                        .addGap(18, 18, 18)
                        .addComponent(sala3))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel1Layout.setVerticalGroup(
            painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(painel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sala1)
                    .addComponent(sala2)
                    .addComponent(sala3))
                .addContainerGap(331, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dashboard Principal", painel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Dashboard Principal");

        jScrollPane1.setViewportView(jPanel2);

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jmenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jmenu1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jmenu2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jmenu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmenu2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jmenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        // TODO add your handling code here:
        btnDashboard.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        // TODO add your handling code here:
        btnDashboard.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnMenuUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuUsuarioMouseEntered
        // TODO add your handling code here:
        btnMenuUsuario.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta1.setIcon(downArrowIcon);
        jmenu.setSize(301, 361);
    }//GEN-LAST:event_btnMenuUsuarioMouseEntered

    private void btnMenuUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuUsuarioMouseExited
        // TODO add your handling code here:
        btnMenuUsuario.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta1.setIcon(leftArrowIcon);
    }//GEN-LAST:event_btnMenuUsuarioMouseExited

    private void jmenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenuMouseExited
        // TODO add your handling code here:
        jmenu.setSize(0, 180);
        btnMenuUsuario.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta1.setIcon(leftArrowIcon);
    }//GEN-LAST:event_jmenuMouseExited

    private void itemAddUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddUserMouseEntered
        jmenu.setSize(301, 361);
        itemAddUser.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta1.setIcon(downArrowIcon);
        btnMenuUsuario.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_itemAddUserMouseEntered

    private void itemAddUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddUserMouseExited
        // TODO add your handling code here:
        itemAddUser.setBackground(Color.WHITE);
        btnMenuUsuario.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta1.setIcon(leftArrowIcon);
    }//GEN-LAST:event_itemAddUserMouseExited

    private void jmenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenuMouseEntered
        // TODO add your handling code here:
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta1.setIcon(downArrowIcon);
        btnMenuUsuario.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_jmenuMouseEntered

    private void itemHistoricoUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemHistoricoUsersMouseEntered
        // TODO add your handling code here:
        jmenu.setSize(301, 361);
        itemHistoricoUsers.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta1.setIcon(downArrowIcon);
        btnMenuUsuario.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_itemHistoricoUsersMouseEntered

    private void itemHistoricoUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemHistoricoUsersMouseExited
        // TODO add your handling code here:
        itemHistoricoUsers.setBackground(Color.WHITE);
        btnMenuUsuario.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta1.setIcon(leftArrowIcon);
    }//GEN-LAST:event_itemHistoricoUsersMouseExited

    private void btnMenuGenSalasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuGenSalasMouseEntered
        jmenu1.setSize(306, 243);
        btnMenuGenSalas.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta2.setIcon(downArrowIcon);
    }//GEN-LAST:event_btnMenuGenSalasMouseEntered

    private void btnMenuGenSalasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuGenSalasMouseExited

    }//GEN-LAST:event_btnMenuGenSalasMouseExited

    private void jmenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu1MouseExited
        jmenu1.setSize(0, 180);
        btnMenuGenSalas.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta2.setIcon(leftArrowIcon);
    }//GEN-LAST:event_jmenu1MouseExited

    private void jmenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu1MouseEntered
        jmenu1.setSize(306, 243);
        btnMenuGenSalas.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta2.setIcon(downArrowIcon);
    }//GEN-LAST:event_jmenu1MouseEntered

    private void itemHistoricoChavesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemHistoricoChavesMouseExited
        itemHistoricoChaves.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta1.setIcon(leftArrowIcon);
    }//GEN-LAST:event_itemHistoricoChavesMouseExited

    private void itemHistoricoChavesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemHistoricoChavesMouseEntered
        jmenu1.setSize(306, 243);
        btnMenuGenSalas.setBackground(Color.LIGHT_GRAY);
        itemHistoricoChaves.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta2.setIcon(downArrowIcon);
    }//GEN-LAST:event_itemHistoricoChavesMouseEntered

    private void itemVisualizarSalasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemVisualizarSalasMouseExited
        itemVisualizarSalas.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta1.setIcon(leftArrowIcon);
    }//GEN-LAST:event_itemVisualizarSalasMouseExited

    private void itemVisualizarSalasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemVisualizarSalasMouseEntered
        jmenu1.setSize(306, 243);
        btnMenuGenSalas.setBackground(Color.LIGHT_GRAY);
        itemVisualizarSalas.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta2.setIcon(downArrowIcon);
    }//GEN-LAST:event_itemVisualizarSalasMouseEntered

    private void itemAddSalaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddSalaMouseExited
        itemAddSala.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta1.setIcon(leftArrowIcon);
    }//GEN-LAST:event_itemAddSalaMouseExited

    private void itemAddSalaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddSalaMouseEntered
        jmenu1.setSize(306, 243);
        btnMenuGenSalas.setBackground(Color.LIGHT_GRAY);
        itemAddSala.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta2.setIcon(downArrowIcon);
    }//GEN-LAST:event_itemAddSalaMouseEntered

    private void btnMenuUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuUserMouseEntered

    }//GEN-LAST:event_btnMenuUserMouseEntered

    private void itemSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSairMouseEntered
        // TODO add your handling code here:
        jmenu2.setSize(270, 290);
        itemSair.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        txtSeta3.setIcon(downArrowIcon);
    }//GEN-LAST:event_itemSairMouseEntered

    private void itemSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemSairMouseExited
        // TODO add your handling code here:
        itemSair.setBackground(Color.WHITE);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        txtSeta3.setIcon(downArrowIcon);
    }//GEN-LAST:event_itemSairMouseExited

    private void btnMenuUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuUserMouseExited

    }//GEN-LAST:event_btnMenuUserMouseExited

    private void jmenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu2MouseEntered
        // TODO add your handling code here:
        jmenu2.setSize(270, 290);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        txtSeta3.setIcon(downArrowIcon);
    }//GEN-LAST:event_jmenu2MouseEntered

    private void jmenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmenu2MouseExited
        // TODO add your handling code here:
        jmenu2.setSize(0, 180);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        txtSeta3.setIcon(leftArrowIcon);
    }//GEN-LAST:event_jmenu2MouseExited

    private void btnMenuUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuUserMouseClicked
        // TODO add your handling code here:
        jmenu2.setSize(270, 290);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        txtSeta3.setIcon(downArrowIcon);
    }//GEN-LAST:event_btnMenuUserMouseClicked

    private void itemAddUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddUserMouseClicked
        // TODO add your handling code here:
        CadastroUserDialog cadastroUser = new CadastroUserDialog(new javax.swing.JFrame(), true);
        cadastroUser.setVisible(true);
    }//GEN-LAST:event_itemAddUserMouseClicked

    private void itemHistoricoUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemHistoricoUsersMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_itemHistoricoUsersMouseClicked

    private void itemAddSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddSalaMouseClicked
        // TODO add your handling code here:
        CadastroSalaDialog cadastroSala = new CadastroSalaDialog(new javax.swing.JFrame(), true);
        cadastroSala.setVisible(true);
    }//GEN-LAST:event_itemAddSalaMouseClicked

    private void itemVisualizarSalasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemVisualizarSalasMouseClicked
        // TODO add your handling code here:
        VisualizarSalasDialog visualizarSalas = new VisualizarSalasDialog(new javax.swing.JFrame(), true);
        visualizarSalas.setVisible(true);
    }//GEN-LAST:event_itemVisualizarSalasMouseClicked

    private void itemHistoricoChavesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemHistoricoChavesMouseClicked
        // TODO add your handling code here:
        VisualizarHistoricoDialog visualizarHistorico = new VisualizarHistoricoDialog(new javax.swing.JFrame(), true);
        visualizarHistorico.setVisible(true);
    }//GEN-LAST:event_itemHistoricoChavesMouseClicked

    private void itemAddPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddPessoaMouseClicked
        // TODO add your handling code here:
        CadastroPessoaDialog cadastroPessoa = new CadastroPessoaDialog(new javax.swing.JFrame(), true);
        cadastroPessoa.setVisible(true);
    }//GEN-LAST:event_itemAddPessoaMouseClicked

    private void itemAddPessoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddPessoaMouseEntered
        // TODO add your handling code here:
        jmenu.setSize(301, 361);
        itemAddPessoa.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta1.setIcon(downArrowIcon);
        btnMenuUsuario.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_itemAddPessoaMouseEntered

    private void itemAddPessoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAddPessoaMouseExited
        // TODO add your handling code here:
        itemAddPessoa.setBackground(Color.WHITE);
        btnMenuUsuario.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta1.setIcon(leftArrowIcon);
    }//GEN-LAST:event_itemAddPessoaMouseExited

    private void txtAddPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddPessoaMouseClicked
        // TODO add your handling code here:
        CadastroPessoaDialog cadastroPessoa = new CadastroPessoaDialog(new javax.swing.JFrame(), true);
        cadastroPessoa.setVisible(true);
        jmenu.setSize(301, 361);
        itemAddPessoa.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta1.setIcon(downArrowIcon);
        btnMenuUsuario.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_txtAddPessoaMouseClicked

    private void txtAddPessoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddPessoaMouseEntered
        // TODO add your handling code here:
        jmenu.setSize(301, 361);
        itemAddPessoa.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta1.setIcon(downArrowIcon);
        btnMenuUsuario.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_txtAddPessoaMouseEntered

    private void txtAddPessoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddPessoaMouseExited
        // TODO add your handling code here:
        itemAddPessoa.setBackground(Color.WHITE);
        btnMenuUsuario.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta1.setIcon(leftArrowIcon);
    }//GEN-LAST:event_txtAddPessoaMouseExited

    private void itemVisualizarUsers1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemVisualizarUsers1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_itemVisualizarUsers1MouseClicked

    private void itemVisualizarUsers1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemVisualizarUsers1MouseEntered
        // TODO add your handling code here:
        jmenu.setSize(301, 361);
        itemVisualizarUsers1.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta1.setIcon(downArrowIcon);
        btnMenuUsuario.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_itemVisualizarUsers1MouseEntered

    private void itemVisualizarUsers1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemVisualizarUsers1MouseExited
        // TODO add your handling code here:
        itemVisualizarUsers1.setBackground(Color.WHITE);
        btnMenuUsuario.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta1.setIcon(leftArrowIcon);
    }//GEN-LAST:event_itemVisualizarUsers1MouseExited

    private void txtVisualizarUsers1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVisualizarUsers1MouseEntered
        // TODO add your handling code here:
        jmenu.setSize(301, 361);
        txtVisualizarUsers1.setBackground(Color.LIGHT_GRAY);
        URL SetaDown = getClass().getResource("/icons/down-arrow.png");
        ImageIcon downArrowIcon = new ImageIcon(SetaDown);
        iconSeta1.setIcon(downArrowIcon);
        btnMenuUsuario.setBackground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_txtVisualizarUsers1MouseEntered

    private void txtVisualizarUsers1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtVisualizarUsers1MouseExited
        // TODO add your handling code here:
        txtVisualizarUsers1.setBackground(Color.WHITE);
        btnMenuUsuario.setBackground(Color.WHITE);
        URL Setaleft = getClass().getResource("/icons/left-arrow.png");
        ImageIcon leftArrowIcon = new ImageIcon(Setaleft);
        iconSeta1.setIcon(leftArrowIcon);
    }//GEN-LAST:event_txtVisualizarUsers1MouseExited

    private void placeHolderNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeHolderNomeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_placeHolderNomeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DashboardScreen().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnDashboard;
    private javax.swing.JPanel btnMenuGenSalas;
    private javax.swing.JPanel btnMenuUser;
    private javax.swing.JPanel btnMenuUsuario;
    private javax.swing.JLabel iconSeta1;
    private javax.swing.JLabel iconSeta2;
    private javax.swing.JPanel itemAddPessoa;
    private javax.swing.JPanel itemAddSala;
    private javax.swing.JPanel itemAddUser;
    private javax.swing.JPanel itemHistoricoChaves;
    private javax.swing.JPanel itemHistoricoUsers;
    private javax.swing.JPanel itemSair;
    private javax.swing.JPanel itemVisualizarSalas;
    private javax.swing.JPanel itemVisualizarUsers1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jmenu;
    private javax.swing.JPanel jmenu1;
    private javax.swing.JPanel jmenu2;
    private javax.swing.JPanel painel1;
    private javax.swing.JLabel placeHolderNome;
    private javax.swing.JButton sala1;
    private javax.swing.JButton sala2;
    private javax.swing.JButton sala3;
    private javax.swing.JLabel txtAddPessoa;
    private javax.swing.JLabel txtAddSala;
    private javax.swing.JLabel txtAddUser;
    private javax.swing.JLabel txtDashboard;
    private javax.swing.JLabel txtGenSalas;
    private javax.swing.JLabel txtHistoricoChaves;
    private javax.swing.JLabel txtHistoricoUsers;
    private javax.swing.JLabel txtNomeUser;
    private javax.swing.JLabel txtSair;
    private javax.swing.JLabel txtSeta3;
    private javax.swing.JLabel txtUsuarios;
    private javax.swing.JLabel txtVisualizarSala;
    private javax.swing.JLabel txtVisualizarUsers1;
    // End of variables declaration//GEN-END:variables
}
