/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Cursor;
import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author adimael
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        // Carrega o ícone
        URL favicon = getClass().getResource("/icons/image 3.png");
        URL userIcon = getClass().getResource("/icons/user.png");
        URL passwordIcon = getClass().getResource("/icons/senha.png");
        URL imagem1 = getClass().getResource("/img/blob-scene-haikei (1).png");
        URL imagem2 = getClass().getResource("/img/blob-scene-haikei (1).png");
        
        if (favicon != null && userIcon != null && passwordIcon != null && imagem1 != null && imagem2 != null) {
            iconSecureKey.setIcon(new ImageIcon(favicon));
            iconUser.setIcon(new ImageIcon(userIcon));
            iconPassword.setIcon(new ImageIcon(passwordIcon));
            img1.setIcon(new ImageIcon(imagem1));
            img2.setIcon(new ImageIcon(imagem2));
        } else {
            System.out.println("Algum icone não foi encontrado na tela de login!");
        }
        
        btnLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLayeredPane();
        jLabelSecureKey = new javax.swing.JLabel();
        iconSecureKey = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        iconPassword = new javax.swing.JLabel();
        placeHolderPass = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelPassword = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        iconUser = new javax.swing.JLabel();
        placeHolderUser = new javax.swing.JLabel();
        jUsernameField = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabelSubTitle = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(988, 647));
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setOpaque(true);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSecureKey.setFont(new java.awt.Font("Inter", 1, 48)); // NOI18N
        jLabelSecureKey.setText("SecureKey");
        bg.add(jLabelSecureKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        iconSecureKey.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/image 3.png")); // NOI18N
        bg.add(iconSecureKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconPassword.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/senha.png")); // NOI18N
        jPanel2.add(iconPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 254, -1, -1));

        placeHolderPass.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        placeHolderPass.setForeground(new java.awt.Color(153, 153, 153));
        placeHolderPass.setText("Digite sua senha....");
        placeHolderPass.setEnabled(false);
        placeHolderPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                placeHolderPassKeyReleased(evt);
            }
        });
        jPanel2.add(placeHolderPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 510, 60));

        jPasswordField1.setBackground(new java.awt.Color(204, 255, 204));
        jPasswordField1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(102, 102, 102));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jPasswordField1.setMinimumSize(new java.awt.Dimension(64, 25));
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 520, 60));

        jLabelPassword.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(7, 164, 121));
        jLabelPassword.setText("Password");
        jPanel2.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabelUsername.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(7, 164, 121));
        jLabelUsername.setText("Username");
        jPanel2.add(jLabelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        iconUser.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/icons/user.png")); // NOI18N
        jPanel2.add(iconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 158, 60, -1));

        placeHolderUser.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        placeHolderUser.setForeground(new java.awt.Color(153, 153, 153));
        placeHolderUser.setText("Digite seu nome de usuário....");
        placeHolderUser.setEnabled(false);
        placeHolderUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                placeHolderUserKeyTyped(evt);
            }
        });
        jPanel2.add(placeHolderUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 510, 60));

        jUsernameField.setBackground(new java.awt.Color(204, 255, 204));
        jUsernameField.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jUsernameField.setForeground(new java.awt.Color(102, 102, 102));
        jUsernameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Inter", 0, 13), new java.awt.Color(255, 255, 255))); // NOI18N
        jUsernameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jUsernameFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jUsernameFieldKeyTyped(evt);
            }
        });
        jPanel2.add(jUsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 520, 60));

        btnLogin.setBackground(new java.awt.Color(0, 102, 0));
        btnLogin.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 250, 60));

        jLabelSubTitle.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelSubTitle.setText("Sistema de gestão");
        jPanel2.add(jLabelSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 670, 580));

        img1.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/img/blob-scene-haikei (1).png")); // NOI18N
        bg.add(img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, -1));

        img2.setIcon(new javax.swing.ImageIcon("/home/adimael/NetBeansProjects/securekey/src/img/blob-scene-haikei (1).png")); // NOI18N
        bg.add(img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 375, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void placeHolderUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeHolderUserKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_placeHolderUserKeyTyped

    private void jUsernameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameFieldKeyTyped

    private void jUsernameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jUsernameFieldKeyReleased
        // TODO add your handling code here:
        if(jUsernameField.getText().isEmpty()) {
            placeHolderUser.setVisible(true);
            placeHolderUser.setEnabled(false);
        } else {
            placeHolderUser.setVisible(false);
            placeHolderUser.setEnabled(false);
        }
    }//GEN-LAST:event_jUsernameFieldKeyReleased

    private void placeHolderPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_placeHolderPassKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_placeHolderPassKeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        // TODO add your handling code here:
        if (new String(jPasswordField1.getPassword()).isEmpty()) {
            placeHolderPass.setVisible(true);
            placeHolderPass.setEnabled(false);
        } else {
            placeHolderPass.setVisible(false);
            placeHolderPass.setEnabled(false);
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        DashboardScreen dashboardScreen = new DashboardScreen();
        
        dashboardScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane bg;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel iconPassword;
    private javax.swing.JLabel iconSecureKey;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSecureKey;
    private javax.swing.JLabel jLabelSubTitle;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jUsernameField;
    private javax.swing.JLabel placeHolderPass;
    private javax.swing.JLabel placeHolderUser;
    // End of variables declaration//GEN-END:variables
}
